language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
  - ant doInstall -buildfile install.xml
install:
  - ant compile -buildfile buildTravis.xml
script:
  - ant test -buildfile buildTravis.xml